#include "ShaderSpirvInternal.h"

#include "ShaderSpirvEmitters.h"
#include "ShaderSpirvTemplates.h"

#include "Emulator/Config.h"
#include "Emulator/Graphics/Objects/VulkanImageFormat.h"

#include <cstdlib>
#include <cstring>

#ifdef KYTY_EMU_ENABLED

namespace Kyty::Libs::Graphics {

const RecompilerFunc* RecompFunc(ShaderInstructionType type, ShaderInstructionFormat::Format format)
{
	static const RecompilerFunc g_recomp_func[] = {
	    // clang-format off
    {Recompile_BufferLoadUbyte_Vdata1VaddrSvSoffsIdxen,  ShaderInstructionType::BufferLoadUbyte,     ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferLoadDword,                             ShaderInstructionType::BufferLoadDword,      ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferLoadDword,                             ShaderInstructionType::BufferLoadDword,      ShaderInstructionFormat::Vdata1Vaddr2SvSoffsOffenIdxen, {""}},
    {Recompile_BufferLoadDwordx2_Vdata2VaddrSvSoffsIdxen,   ShaderInstructionType::BufferLoadDwordx2,    ShaderInstructionFormat::Vdata2VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferLoadDwordx3_Vdata3VaddrSvSoffsIdxen,   ShaderInstructionType::BufferLoadDwordx3,    ShaderInstructionFormat::Vdata3VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferLoadDwordx4_Vdata4VaddrSvSoffsIdxen,   ShaderInstructionType::BufferLoadDwordx4,    ShaderInstructionFormat::Vdata4VaddrSvSoffsIdxen,        {""}},
	{Recompile_BufferAtomicAdd_Vdata1VaddrSvSoffsIdxen,     ShaderInstructionType::BufferAtomicAdd,     ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferAtomic_XXX_Vdata1VaddrSvSoffsIdxen,    ShaderInstructionType::BufferAtomicSub,     ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {"OpAtomicISub"}},
    {Recompile_BufferAtomic_XXX_Vdata1VaddrSvSoffsIdxen,    ShaderInstructionType::BufferAtomicSmin,    ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {"OpAtomicSMin"}},
    {Recompile_BufferAtomic_XXX_Vdata1VaddrSvSoffsIdxen,    ShaderInstructionType::BufferAtomicUmin,    ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {"OpAtomicUMin"}},
    {Recompile_BufferAtomic_XXX_Vdata1VaddrSvSoffsIdxen,    ShaderInstructionType::BufferAtomicSmax,    ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {"OpAtomicSMax"}},
    {Recompile_BufferAtomic_XXX_Vdata1VaddrSvSoffsIdxen,    ShaderInstructionType::BufferAtomicUmax,    ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {"OpAtomicUMax"}},
    {Recompile_BufferAtomic_XXX_Vdata1VaddrSvSoffsIdxen,    ShaderInstructionType::BufferAtomicAnd,     ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {"OpAtomicAnd"}},
    {Recompile_BufferAtomic_XXX_Vdata1VaddrSvSoffsIdxen,    ShaderInstructionType::BufferAtomicOr,      ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {"OpAtomicOr"}},
    {Recompile_BufferAtomic_XXX_Vdata1VaddrSvSoffsIdxen,    ShaderInstructionType::BufferAtomicXor,     ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {"OpAtomicXor"}},
    {Recompile_BufferLoadFormatX_Vdata1VaddrSvSoffsIdxen,   ShaderInstructionType::BufferLoadFormatX,    ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferLoadFormatXyzw_Vdata4VaddrSvSoffsIdxen, ShaderInstructionType::BufferLoadFormatXyzw, ShaderInstructionFormat::Vdata4VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferStoreDword_Vdata1VaddrSvSoffsIdxen,    ShaderInstructionType::BufferStoreDword,     ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferStoreDword_Vdata1VaddrSvSoffsIdxen,    ShaderInstructionType::BufferStoreDword,     ShaderInstructionFormat::Vdata1VaddrSvSoffsOffen,        {""}},
    {Recompile_BufferStoreDwordx2_Vdata2VaddrSvSoffsIdxen,  ShaderInstructionType::BufferStoreDwordx2,   ShaderInstructionFormat::Vdata2VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferStoreDwordx3_Vdata3VaddrSvSoffsIdxen,  ShaderInstructionType::BufferStoreDwordx3,   ShaderInstructionFormat::Vdata3VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferStoreDwordx4_Vdata4VaddrSvSoffsIdxen,  ShaderInstructionType::BufferStoreDwordx4,   ShaderInstructionFormat::Vdata4VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferStoreFormatX_Vdata1VaddrSvSoffsIdxen,  ShaderInstructionType::BufferStoreFormatX,   ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferStoreFormatXy_Vdata2VaddrSvSoffsIdxen, ShaderInstructionType::BufferStoreFormatXy,  ShaderInstructionFormat::Vdata2VaddrSvSoffsIdxen,        {""}},
    {Recompile_BufferStoreFormatXyzw_Vdata4VaddrSvSoffsIdxen, ShaderInstructionType::BufferStoreFormatXyzw, ShaderInstructionFormat::Vdata4VaddrSvSoffsIdxen,      {""}},

    {Recompile_Fetch,                                       ShaderInstructionType::FetchX,               ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxen,        {""}},
    {Recompile_Fetch,                                       ShaderInstructionType::FetchXy,              ShaderInstructionFormat::Vdata2VaddrSvSoffsIdxen,        {""}},
    {Recompile_Fetch,                                       ShaderInstructionType::FetchXyz,             ShaderInstructionFormat::Vdata3VaddrSvSoffsIdxen,        {""}},
    {Recompile_Fetch,                                       ShaderInstructionType::FetchXyzw,            ShaderInstructionFormat::Vdata4VaddrSvSoffsIdxen,        {""}},

    {Recompile_DsAppend_VdstGds,                           ShaderInstructionType::DsAppend,            ShaderInstructionFormat::VdstGds,                        {""}},
    {Recompile_DsConsume_VdstGds,                          ShaderInstructionType::DsConsume,           ShaderInstructionFormat::VdstGds,                        {""}},
	{Recompile_DsAddU32_VaddrVdataOffset,                  ShaderInstructionType::DsAddU32,            ShaderInstructionFormat::VaddrVdataOffset,               {""}},
    {Recompile_DsAtomic_XXX_VaddrVdataOffset,              ShaderInstructionType::DsSubU32,            ShaderInstructionFormat::VaddrVdataOffset,               {"OpAtomicISub"}},
    {Recompile_DsAtomic_XXX_VaddrVdataOffset,              ShaderInstructionType::DsMinU32,            ShaderInstructionFormat::VaddrVdataOffset,               {"OpAtomicUMin"}},
    {Recompile_DsAtomic_XXX_VaddrVdataOffset,              ShaderInstructionType::DsMaxU32,            ShaderInstructionFormat::VaddrVdataOffset,               {"OpAtomicUMax"}},
    {Recompile_DsAtomic_XXX_VaddrVdataOffset,              ShaderInstructionType::DsMinI32,            ShaderInstructionFormat::VaddrVdataOffset,               {"OpAtomicSMin"}},
    {Recompile_DsAtomic_XXX_VaddrVdataOffset,              ShaderInstructionType::DsMaxI32,            ShaderInstructionFormat::VaddrVdataOffset,               {"OpAtomicSMax"}},
    {Recompile_DsAtomic_XXX_VaddrVdataOffset,              ShaderInstructionType::DsAndB32,            ShaderInstructionFormat::VaddrVdataOffset,               {"OpAtomicAnd"}},
    {Recompile_DsAtomic_XXX_VaddrVdataOffset,              ShaderInstructionType::DsOrB32,             ShaderInstructionFormat::VaddrVdataOffset,               {"OpAtomicOr"}},
    {Recompile_DsAtomic_XXX_VaddrVdataOffset,              ShaderInstructionType::DsXorB32,            ShaderInstructionFormat::VaddrVdataOffset,               {"OpAtomicXor"}},
    {Recompile_DsAtomicIncDec_VaddrOffset,                 ShaderInstructionType::DsIncU32,            ShaderInstructionFormat::VaddrOffset,                    {"OpAtomicIIncrement"}},
    {Recompile_DsAtomicIncDec_VaddrOffset,                 ShaderInstructionType::DsDecU32,            ShaderInstructionFormat::VaddrOffset,                    {"OpAtomicIDecrement"}},
	{Recompile_DsReadB32_VdstVaddrOffset,                  ShaderInstructionType::DsReadB32,           ShaderInstructionFormat::VdstVaddrOffset,                {""}},
    {Recompile_DsWriteB32_VaddrVdataOffset,                ShaderInstructionType::DsWriteB32,          ShaderInstructionFormat::VaddrVdataOffset,                {""}},
    {Recompile_DsRead2B32_Vdst2VaddrOffset01,              ShaderInstructionType::DsRead2B32,          ShaderInstructionFormat::Vdst2VaddrOffset01,              {""}},
    {Recompile_SBarrier_Empty,                             ShaderInstructionType::SBarrier,             ShaderInstructionFormat::Empty,                            {""}},

    {Recompile_Exp_MrtNullDone,                            ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt0OffOffComprVmDone,          {""}},
    {Recompile_Exp_MrtNullDone,                            ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt1OffOffComprVmDone,          {""}},
    {Recompile_Exp_MrtNullDone,                            ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt2OffOffComprVmDone,          {""}},
    {Recompile_Exp_MrtNullDone,                            ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt3OffOffComprVmDone,          {""}},
    {Recompile_Exp_Mrt_Compr_Vsrc0Vsrc1,                   ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt0Vsrc0Vsrc1ComprVmDone,      {"outColor"}},
    {Recompile_Exp_Mrt_Compr_Vsrc0Vsrc1,                   ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt1Vsrc0Vsrc1ComprVm,          {"outColor1"}},
    {Recompile_Exp_Mrt_Compr_Vsrc0Vsrc1,                   ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt2Vsrc0Vsrc1ComprVm,          {"outColor2"}},
    {Recompile_Exp_Mrt_Compr_Vsrc0Vsrc1,                   ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt3Vsrc0Vsrc1ComprVm,          {"outColor3"}},
    {Recompile_Exp_Mrt_Full_Vsrc0Vsrc1Vsrc2Vsrc3,          ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt0Vsrc0Vsrc1Vsrc2Vsrc3VmDone, {"outColor"}},
    {Recompile_Exp_Mrt_Full_Vsrc0Vsrc1Vsrc2Vsrc3,          ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt1Vsrc0Vsrc1Vsrc2Vsrc3Vm,     {"outColor1"}},
    {Recompile_Exp_Mrt_Full_Vsrc0Vsrc1Vsrc2Vsrc3,          ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt2Vsrc0Vsrc1Vsrc2Vsrc3Vm,     {"outColor2"}},
    {Recompile_Exp_Mrt_Full_Vsrc0Vsrc1Vsrc2Vsrc3,          ShaderInstructionType::Exp,                 ShaderInstructionFormat::Mrt3Vsrc0Vsrc1Vsrc2Vsrc3Vm,     {"outColor3"}},
    {Recompile_Exp_Param_XXX_Vsrc0Vsrc1Vsrc2Vsrc3,         ShaderInstructionType::Exp,                 ShaderInstructionFormat::Param0Vsrc0Vsrc1Vsrc2Vsrc3,     {"param0"}},
    {Recompile_Exp_Param_XXX_Vsrc0Vsrc1Vsrc2Vsrc3,         ShaderInstructionType::Exp,                 ShaderInstructionFormat::Param1Vsrc0Vsrc1Vsrc2Vsrc3,     {"param1"}},
    {Recompile_Exp_Param_XXX_Vsrc0Vsrc1Vsrc2Vsrc3,         ShaderInstructionType::Exp,                 ShaderInstructionFormat::Param2Vsrc0Vsrc1Vsrc2Vsrc3,     {"param2"}},
    {Recompile_Exp_Param_XXX_Vsrc0Vsrc1Vsrc2Vsrc3,         ShaderInstructionType::Exp,                 ShaderInstructionFormat::Param3Vsrc0Vsrc1Vsrc2Vsrc3,     {"param3"}},
	{Recompile_Exp_Param_XXX_Vsrc0Vsrc1Vsrc2Vsrc3,         ShaderInstructionType::Exp,                 ShaderInstructionFormat::Param4Vsrc0Vsrc1Vsrc2Vsrc3,     {"param4"}},
	{Recompile_Exp_Param_XXX_Vsrc0Vsrc1Vsrc2Vsrc3,         ShaderInstructionType::Exp,                 ShaderInstructionFormat::Param5Vsrc0Vsrc1Vsrc2Vsrc3,     {"param5"}},
	{Recompile_Exp_Param_XXX_Vsrc0Vsrc1Vsrc2Vsrc3,         ShaderInstructionType::Exp,                 ShaderInstructionFormat::Param6Vsrc0Vsrc1Vsrc2Vsrc3,     {"param6"}},
    {Recompile_Exp_Pos0Vsrc0Vsrc1Vsrc2Vsrc3Done,           ShaderInstructionType::Exp,                 ShaderInstructionFormat::Pos0Vsrc0Vsrc1Vsrc2Vsrc3Done,   {""}},
    {Recompile_Exp_PrimVsrc0OffOffOffDone,                 ShaderInstructionType::Exp,                 ShaderInstructionFormat::PrimVsrc0OffOffOffDone,         {""}},

	{Recompile_ImageLoad_VdataVaddr3StDmask,                ShaderInstructionType::ImageLoad,           ShaderInstructionFormat::VdataVaddr3StDmask,             {""}},
	{Recompile_ImageLoad_VdataVaddr3StDmask,                ShaderInstructionType::ImageLoad,           ShaderInstructionFormat::Vdata4Vaddr3StDmaskF,           {""}},
	{Recompile_ImageGetResinfo_VdataVaddrStDmask,           ShaderInstructionType::ImageGetResinfo,     ShaderInstructionFormat::VdataVaddrStDmask,              {""}},
	{Recompile_ImageGather4_Vdata4Vaddr3StSsMimgDmask,      ShaderInstructionType::ImageGather4,        ShaderInstructionFormat::Vdata4Vaddr3StSsMimgDmask,      {""}},
	{Recompile_ImageSample_Vdata1Vaddr3StSsDmask1,         ShaderInstructionType::ImageSample,         ShaderInstructionFormat::Vdata1Vaddr3StSsDmask1,         {""}},
    {Recompile_ImageSample_Vdata1Vaddr3StSsDmask2,         ShaderInstructionType::ImageSample,         ShaderInstructionFormat::Vdata1Vaddr3StSsDmask2,         {""}},
    {Recompile_ImageSample_Vdata1Vaddr3StSsDmask4,         ShaderInstructionType::ImageSample,         ShaderInstructionFormat::Vdata1Vaddr3StSsDmask4,         {""}},
    {Recompile_ImageSample_Vdata1Vaddr3StSsDmask8,         ShaderInstructionType::ImageSample,         ShaderInstructionFormat::Vdata1Vaddr3StSsDmask8,         {""}},
    {Recompile_ImageSample_Vdata2Vaddr3StSsDmask3,         ShaderInstructionType::ImageSample,         ShaderInstructionFormat::Vdata2Vaddr3StSsDmask3,         {""}},
    {Recompile_ImageSample_Vdata2Vaddr3StSsDmask5,         ShaderInstructionType::ImageSample,         ShaderInstructionFormat::Vdata2Vaddr3StSsDmask5,         {""}},
    {Recompile_ImageSample_Vdata2Vaddr3StSsDmask9,         ShaderInstructionType::ImageSample,         ShaderInstructionFormat::Vdata2Vaddr3StSsDmask9,         {""}},
    {Recompile_ImageSample_Vdata2Vaddr3StSsDmaskA,         ShaderInstructionType::ImageSample,         ShaderInstructionFormat::Vdata2Vaddr3StSsDmaskA,         {""}},
    {Recompile_ImageSample_Vdata3Vaddr3StSsDmask7,         ShaderInstructionType::ImageSample,         ShaderInstructionFormat::Vdata3Vaddr3StSsDmask7,         {""}},
    {Recompile_ImageSample_Vdata3Vaddr3StSsDmaskB,         ShaderInstructionType::ImageSample,         ShaderInstructionFormat::Vdata3Vaddr3StSsDmaskB,         {""}},
	{Recompile_ImageSample_Vdata4Vaddr3StSsDmaskF,         ShaderInstructionType::ImageSample,         ShaderInstructionFormat::Vdata4Vaddr3StSsDmaskF,         {""}},
	{Recompile_ImageSampleL_Vdata3Vaddr3StSsDmask7,        ShaderInstructionType::ImageSampleL,        ShaderInstructionFormat::Vdata3Vaddr3StSsDmask7,         {""}},
	{Recompile_ImageSampleL_Vdata4Vaddr3StSsDmaskF,        ShaderInstructionType::ImageSampleL,        ShaderInstructionFormat::Vdata4Vaddr3StSsDmaskF,         {""}},
    {Recompile_ImageSampleLz_Vdata1Vaddr3StSsDmask1,       ShaderInstructionType::ImageSampleLz,       ShaderInstructionFormat::Vdata1Vaddr3StSsDmask1,         {""}},
    {Recompile_ImageSampleLz_Vdata1Vaddr3StSsDmask2,       ShaderInstructionType::ImageSampleLz,       ShaderInstructionFormat::Vdata1Vaddr3StSsDmask2,         {""}},
    {Recompile_ImageSampleLz_Vdata1Vaddr3StSsDmask8,       ShaderInstructionType::ImageSampleLz,       ShaderInstructionFormat::Vdata1Vaddr3StSsDmask8,         {""}},
    {Recompile_ImageSampleLz_Vdata2Vaddr3StSsDmask3,       ShaderInstructionType::ImageSampleLz,       ShaderInstructionFormat::Vdata2Vaddr3StSsDmask3,         {""}},
    {Recompile_ImageSampleLz_Vdata3Vaddr3StSsDmask7,       ShaderInstructionType::ImageSampleLz,       ShaderInstructionFormat::Vdata3Vaddr3StSsDmask7,         {""}},
    {Recompile_ImageSampleLz_Vdata4Vaddr3StSsDmaskF,       ShaderInstructionType::ImageSampleLz,       ShaderInstructionFormat::Vdata4Vaddr3StSsDmaskF,         {""}},
    {Recompile_ImageSampleLzO_Vdata3Vaddr4StSsDmask7,      ShaderInstructionType::ImageSampleLzO,      ShaderInstructionFormat::Vdata3Vaddr4StSsDmask7,         {""}},
    {Recompile_ImageStore_VdataVaddr3StDmask,              ShaderInstructionType::ImageStore,          ShaderInstructionFormat::VdataVaddr3StDmask,             {""}},
	{Recompile_ImageStore_VdataVaddr3StDmask,              ShaderInstructionType::ImageStore,          ShaderInstructionFormat::Vdata4Vaddr3StDmaskF,           {""}},
    {Recompile_ImageStoreMip_Vdata4Vaddr4StDmaskF,         ShaderInstructionType::ImageStoreMip,       ShaderInstructionFormat::Vdata4Vaddr4StDmaskF,           {""}},

    {Recompile_SBufferLoadDword_SdstSvSoffset,             ShaderInstructionType::SBufferLoadDword,    ShaderInstructionFormat::SdstSvSoffset,                  {""}},
    {Recompile_SBufferLoadDwordx2_Sdst2SvSoffset,          ShaderInstructionType::SBufferLoadDwordx2,  ShaderInstructionFormat::Sdst2SvSoffset,                 {""}},
    {Recompile_SBufferLoadDwordx4_Sdst4SvSoffset,          ShaderInstructionType::SBufferLoadDwordx4,  ShaderInstructionFormat::Sdst4SvSoffset,                 {""}},
    {Recompile_SBufferLoadDwordx8_Sdst8SvSoffset,          ShaderInstructionType::SBufferLoadDwordx8,  ShaderInstructionFormat::Sdst8SvSoffset,                 {""}},
    {Recompile_SBufferLoadDwordx16_Sdst16SvSoffset,        ShaderInstructionType::SBufferLoadDwordx16, ShaderInstructionFormat::Sdst16SvSoffset,                {""}},

    {Recompile_SCbranch_XXX_Label,                         ShaderInstructionType::SCbranchExecz,       ShaderInstructionFormat::Label,                          {"%cc_u_<index> = OpLoad %uint %exec_lo\n%cc_lane_b_<index> = OpINotEqual %bool %cc_u_<index> %uint_0\n%cc_any_<index> = OpGroupNonUniformAny %bool %uint_3 %cc_lane_b_<index>",  "%cc_b_<index> = OpLogicalNot %bool %cc_any_<index>"}},
    {Recompile_SCbranch_XXX_Label,                         ShaderInstructionType::SCbranchScc0,        ShaderInstructionFormat::Label,                          {"%cc_u_<index> = OpLoad %uint %scc",    "%cc_b_<index> = OpIEqual    %bool %cc_u_<index> %uint_0"}},
    {Recompile_SCbranch_XXX_Label,                         ShaderInstructionType::SCbranchScc1,        ShaderInstructionFormat::Label,                          {"%cc_u_<index> = OpLoad %uint %scc",    "%cc_b_<index> = OpIEqual    %bool %cc_u_<index> %uint_1"}},
    {Recompile_SCbranch_XXX_Label,                         ShaderInstructionType::SCbranchVccz,        ShaderInstructionFormat::Label,                          {"%cc_u_<index> = OpLoad %uint %vcc_lo\n%cc_lane_b_<index> = OpINotEqual %bool %cc_u_<index> %uint_0\n%cc_any_<index> = OpGroupNonUniformAny %bool %uint_3 %cc_lane_b_<index>", "%cc_b_<index> = OpLogicalNot %bool %cc_any_<index>"}},
    {Recompile_SCbranch_XXX_Label,                         ShaderInstructionType::SCbranchVccnz,       ShaderInstructionFormat::Label,                          {"%cc_u_<index> = OpLoad %uint %vcc_lo\n%cc_lane_b_<index> = OpINotEqual %bool %cc_u_<index> %uint_0", "%cc_b_<index> = OpGroupNonUniformAny %bool %uint_3 %cc_lane_b_<index>"}},
    {Recompile_SBranch_Label,                              ShaderInstructionType::SBranch,             ShaderInstructionFormat::Label,                          {""}},

    {Recompile_SEndpgm_Empty,                              ShaderInstructionType::SEndpgm,             ShaderInstructionFormat::Empty,                          {""}},
    {Recompile_SSetpcB64_Saddr,                            ShaderInstructionType::SSetpcB64,           ShaderInstructionFormat::Saddr,                          {""}},

	{Recompile_SLoadDword_SdstSbaseSoffset,                ShaderInstructionType::SLoadDword,          ShaderInstructionFormat::SdstSbaseSoffset,               {""}},
	{Recompile_SLoadDwordx2_Sdst2Ssrc02Ssrc1,              ShaderInstructionType::SLoadDwordx2,        ShaderInstructionFormat::Sdst2Ssrc02Ssrc1,               {""}},
    {Recompile_SLoadDwordx4_Sdst4SbaseSoffset,             ShaderInstructionType::SLoadDwordx4,        ShaderInstructionFormat::Sdst4SbaseSoffset,              {""}},
    {Recompile_SLoadDwordx8_Sdst8SbaseSoffset,             ShaderInstructionType::SLoadDwordx8,        ShaderInstructionFormat::Sdst8SbaseSoffset,              {""}},

    {Recompile_S_XXX_B64_Sdst2Ssrc02Ssrc12, ShaderInstructionType::SAndn2B64,   ShaderInstructionFormat::Sdst2Ssrc02Ssrc12, {"%ta_<index> = OpNot %uint %t2_<index>",
                                                                                                                             "%tb_<index> = OpBitwiseAnd %uint %t0_<index> %ta_<index>",
                                                                                                                             "%tc_<index> = OpNot %uint %t3_<index>",
                                                                                                                             "%td_<index> = OpBitwiseAnd %uint %t1_<index> %tc_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B64_Sdst2Ssrc02Ssrc12, ShaderInstructionType::SOrn2B64,    ShaderInstructionFormat::Sdst2Ssrc02Ssrc12, {"%ta_<index> = OpNot %uint %t2_<index>",
                                                                                                                             "%tb_<index> = OpBitwiseOr %uint %t0_<index> %ta_<index>",
                                                                                                                             "%tc_<index> = OpNot %uint %t3_<index>",
                                                                                                                             "%td_<index> = OpBitwiseOr %uint %t1_<index> %tc_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B64_Sdst2Ssrc02Ssrc12, ShaderInstructionType::SAndB64,     ShaderInstructionFormat::Sdst2Ssrc02Ssrc12, {"%tb_<index> = OpBitwiseAnd %uint %t0_<index> %t2_<index>",
                                                                                                                             "%td_<index> = OpBitwiseAnd %uint %t1_<index> %t3_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B64_Sdst2Ssrc02Ssrc12, ShaderInstructionType::SNorB64,     ShaderInstructionFormat::Sdst2Ssrc02Ssrc12, {"%ta_<index> = OpBitwiseOr %uint %t0_<index> %t2_<index>",
                                                                                                                             "%tb_<index> = OpNot %uint %ta_<index>",
                                                                                                                             "%tc_<index> = OpBitwiseOr %uint %t1_<index> %t3_<index>",
                                                                                                                             "%td_<index> = OpNot %uint %tc_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B64_Sdst2Ssrc02Ssrc12, ShaderInstructionType::SNandB64,    ShaderInstructionFormat::Sdst2Ssrc02Ssrc12, {"%ta_<index> = OpBitwiseAnd %uint %t0_<index> %t2_<index>",
                                                                                                                             "%tb_<index> = OpNot %uint %ta_<index>",
                                                                                                                             "%tc_<index> = OpBitwiseAnd %uint %t1_<index> %t3_<index>",
                                                                                                                             "%td_<index> = OpNot %uint %tc_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B64_Sdst2Ssrc02Ssrc12, ShaderInstructionType::SXnorB64,    ShaderInstructionFormat::Sdst2Ssrc02Ssrc12, {"%ta_<index> = OpBitwiseXor %uint %t0_<index> %t2_<index>",
                                                                                                                             "%tb_<index> = OpNot %uint %ta_<index>",
                                                                                                                             "%tc_<index> = OpBitwiseXor %uint %t1_<index> %t3_<index>",
                                                                                                                             "%td_<index> = OpNot %uint %tc_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B64_Sdst2Ssrc02Ssrc12, ShaderInstructionType::SOrB64,      ShaderInstructionFormat::Sdst2Ssrc02Ssrc12, {"%tb_<index> = OpBitwiseOr %uint %t0_<index> %t2_<index>",
                                                                                                                             "%td_<index> = OpBitwiseOr %uint %t1_<index> %t3_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B64_Sdst2Ssrc02Ssrc12, ShaderInstructionType::SXorB64,     ShaderInstructionFormat::Sdst2Ssrc02Ssrc12, {"%tb_<index> = OpBitwiseXor %uint %t0_<index> %t2_<index>",
                                                                                                                             "%td_<index> = OpBitwiseXor %uint %t1_<index> %t3_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B64_Sdst2Ssrc02Ssrc12, ShaderInstructionType::SCselectB64, ShaderInstructionFormat::Sdst2Ssrc02Ssrc12, {"%ts_<index> = OpLoad %uint %scc",
                                                                                                                             "%tsb_<index> = OpINotEqual %bool %ts_<index> %uint_0",
                                                                                                                             "%tb_<index> = OpSelect %uint %tsb_<index> %t0_<index> %t2_<index>",
                                                                                                                             "%td_<index> = OpSelect %uint %tsb_<index> %t1_<index> %t3_<index>" }, SccCheck::None},

    {Recompile_S_Bfe_U64_Sdst2Ssrc02Ssrc1,  ShaderInstructionType::SBfeU64,     ShaderInstructionFormat::Sdst2Ssrc02Ssrc1,  {"", ""} , SccCheck::NonZero},
    {Recompile_S_Lshl_B64_Sdst2Ssrc02Ssrc1, ShaderInstructionType::SLshlB64,    ShaderInstructionFormat::Sdst2Ssrc02Ssrc1,  {"", ""} , SccCheck::NonZero},
    {Recompile_S_Lshr_B64_Sdst2Ssrc02Ssrc1, ShaderInstructionType::SLshrB64,    ShaderInstructionFormat::Sdst2Ssrc02Ssrc1,  {"", ""} , SccCheck::NonZero},

    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SAndB32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpBitwiseAnd %uint %t0_<index> %t1_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SBfmB32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%tcount_<index> = OpBitwiseAnd %uint %t0_<index> %uint_31", "%toffset_<index> = OpBitwiseAnd %uint %t1_<index> %uint_31", "%t_<index> = OpBitFieldInsert %uint %uint_0 %uint_0xffffffff %toffset_<index> %tcount_<index>"}, SccCheck::None},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SCselectB32,     ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t22_<index> = OpLoad %uint %scc", "%t2_<index> = OpINotEqual %bool %t22_<index> %uint_0", "%t_<index> = OpSelect %uint %t2_<index> %t0_<index> %t1_<index>"}, SccCheck::None},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SLshlB32,        ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ts_<index> = OpBitwiseAnd %uint %t1_<index> %uint_31", "%t_<index> = OpShiftLeftLogical %uint %t0_<index> %ts_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SLshrB32,        ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ts_<index> = OpBitwiseAnd %uint %t1_<index> %uint_31", "%t_<index> = OpShiftRightLogical %uint %t0_<index> %ts_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SOrB32,          ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpBitwiseOr %uint %t0_<index> %t1_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SXorB32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpBitwiseXor %uint %t0_<index> %t1_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SAndn2B32,       ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ta_<index> = OpNot %uint %t1_<index>", "%t_<index> = OpBitwiseAnd %uint %t0_<index> %ta_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SOrn2B32,        ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ta_<index> = OpNot %uint %t1_<index>", "%t_<index> = OpBitwiseOr %uint %t0_<index> %ta_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SNandB32,        ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ta_<index> = OpBitwiseAnd %uint %t0_<index> %t1_<index>", "%t_<index> = OpNot %uint %ta_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SNorB32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ta_<index> = OpBitwiseOr %uint %t0_<index> %t1_<index>", "%t_<index> = OpNot %uint %ta_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SXnorB32,        ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ta_<index> = OpBitwiseXor %uint %t0_<index> %t1_<index>", "%t_<index> = OpNot %uint %ta_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SAshrI32,        ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ts_<index> = OpBitwiseAnd %uint %t1_<index> %uint_31", "%t_<index> = OpShiftRightArithmetic %uint %t0_<index> %ts_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_I32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SMinI32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %int %GLSL_std_450 SMin %t0_<index> %t1_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_I32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SMaxI32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %int %GLSL_std_450 SMax %t0_<index> %t1_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_U32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SMinU32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %uint %GLSL_std_450 UMin %t0_<index> %t1_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_U32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SMaxU32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %uint %GLSL_std_450 UMax %t0_<index> %t1_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_I32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SAddI32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpIAdd %int %t0_<index> %t1_<index>"}, SccCheck::OverflowAdd},
    {Recompile_S_XXX_I32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SMulI32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpIMul %int %t0_<index> %t1_<index>"}, SccCheck::None},
    {Recompile_S_XXX_I32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SSubI32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpISub %int %t0_<index> %t1_<index>"}, SccCheck::OverflowSub},
    {Recompile_S_XXX_U32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SAddcU32,        ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%tscc_<index> = OpLoad %uint %scc", "%ts_<index> = OpFunctionCall %v2uint %addc %t0_<index> %t1_<index> %tscc_<index>", "%t_<index> = OpCompositeExtract %uint %ts_<index> 0", "%carry_<index> = OpCompositeExtract %uint %ts_<index> 1"}, SccCheck::CarryOut},
    {Recompile_S_XXX_U32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SAddU32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ts_<index> = OpIAddCarry %ResTypeU %t0_<index> %t1_<index>", "%t_<index> = OpCompositeExtract %uint %ts_<index> 0", "%carry_<index> = OpCompositeExtract %uint %ts_<index> 1"}, SccCheck::CarryOut},
    {Recompile_S_XXX_U32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SBfeU32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%to_<index> = OpBitFieldUExtract %uint %t1_<index> %uint_0  %uint_5", "%ts_<index> = OpBitFieldUExtract %uint %t1_<index> %uint_16 %uint_7", "%t_<index> = OpBitFieldUExtract %uint %t0_<index> %to_<index> %ts_<index>"}, SccCheck::NonZero},
    {Recompile_S_XXX_U32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SLshl4AddU32,    ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ts_<index> = OpFunctionCall %v2uint %lshl_add %t0_<index> %t1_<index> %uint_4", "%t_<index> = OpCompositeExtract %uint %ts_<index> 0", "%carry_<index> = OpCompositeExtract %uint %ts_<index> 1"}, SccCheck::CarryOut},
    {Recompile_S_XXX_U32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::SMulHiU32,       ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFunctionCall %uint %mul_hi_uint %t0_<index> %t1_<index>"}, SccCheck::None},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VAndB32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpBitwiseAnd %uint %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VAddI32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpIAdd %uint %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VSubI32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpISub %uint %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VSubrevI32,      ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpISub %uint %t1_<index> %t0_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VBcntU32B32,     ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%tb_<index> = OpBitCount %int %t0_<index>", "%tbu_<index> = OpBitcast %uint %tb_<index>", "%t_<index> = OpIAdd %uint %tbu_<index> %t1_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VBfmB32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%tcount_<index> = OpBitwiseAnd %uint %t0_<index> %uint_31", "%toffset_<index> = OpBitwiseAnd %uint %t1_<index> %uint_31", "%t_<index> = OpBitFieldInsert %uint %uint_0 %uint_0xffffffff %toffset_<index> %tcount_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VLshlB32,        ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ts_<index> = OpBitwiseAnd %uint %t1_<index> %uint_31", "%t_<index> = OpShiftLeftLogical %uint %t0_<index> %ts_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VLshlrevB32,     ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ts_<index> = OpBitwiseAnd %uint %t0_<index> %uint_31", "%t_<index> = OpShiftLeftLogical %uint %t1_<index> %ts_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VLshrB32,        ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ts_<index> = OpBitwiseAnd %uint %t1_<index> %uint_31", "%t_<index> = OpShiftRightLogical %uint %t0_<index> %ts_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VLshrrevB32,     ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ts_<index> = OpBitwiseAnd %uint %t0_<index> %uint_31", "%t_<index> = OpShiftRightLogical %uint %t1_<index> %ts_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMulHiU32,       ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFunctionCall %uint %mul_hi_uint %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMulLoU32,       ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFunctionCall %uint %mul_lo_uint %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMulU32U24,      ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%tu0_<index> = OpBitwiseAnd %uint %t0_<index> %uint_0x00ffffff", "%tu1_<index> = OpBitwiseAnd %uint %t1_<index> %uint_0x00ffffff", "%t_<index> = OpFunctionCall %uint %mul_lo_uint %tu0_<index> %tu1_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMinU32,          ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %uint %GLSL_std_450 UMin %t0_<index> %t1_<index>"}},
	{Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMaxU32,          ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %uint %GLSL_std_450 UMax %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VOrB32,          ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpBitwiseOr %uint %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VXnorB32,        ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%tx_<index> = OpBitwiseXor %uint %t0_<index> %t1_<index>", "%t_<index> = OpNot %uint %tx_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VXorB32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpBitwiseXor %uint %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VAddF32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFAdd %float %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMacF32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %float %GLSL_std_450 Fma %t0_<index> %t1_<index> %tdst_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMaxF32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %float %GLSL_std_450 FMax %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMinF32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %float %GLSL_std_450 FMin %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMulF32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFMul %float %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VSubF32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFSub %float %t0_<index> %t1_<index>"}},
    {Recompile_VF16_XXX_VdstVsrc0Vsrc1,            ShaderInstructionType::VAddF16,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFAdd %float %hf0_<index> %hf1_<index>"}},
    {Recompile_VF16_XXX_VdstVsrc0Vsrc1,            ShaderInstructionType::VSubF16,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFSub %float %hf0_<index> %hf1_<index>"}},
    {Recompile_VF16_XXX_VdstVsrc0Vsrc1,            ShaderInstructionType::VSubrevF16,      ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFSub %float %hf1_<index> %hf0_<index>"}},
    {Recompile_VF16_XXX_VdstVsrc0Vsrc1,            ShaderInstructionType::VMulF16,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFMul %float %hf0_<index> %hf1_<index>"}},
    {Recompile_VF16_XXX_VdstVsrc0Vsrc1,            ShaderInstructionType::VMaxF16,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %float %GLSL_std_450 FMax %hf0_<index> %hf1_<index>"}},
    {Recompile_VF16_XXX_VdstVsrc0Vsrc1,            ShaderInstructionType::VMinF16,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %float %GLSL_std_450 FMin %hf0_<index> %hf1_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VSubrevF32,      ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFSub %float %t1_<index> %t0_<index>"}},
    {Recompile_V_XXX_I32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VAshrI32,        ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ts_<index> = OpBitwiseAnd %int %t1_<index> %int_31", "%t_<index> = OpShiftRightArithmetic %int %t0_<index> %ts_<index>"}},
    {Recompile_V_XXX_I32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VAshrrevI32,     ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%ts_<index> = OpBitwiseAnd %int %t0_<index> %int_31", "%t_<index> = OpShiftRightArithmetic %int %t1_<index> %ts_<index>"}},
	{Recompile_V_XXX_I32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMulHiI32,       ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFunctionCall %int %mul_hi_int %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_I32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMulLoI32,       ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpFunctionCall %int %mul_lo_int %t0_<index> %t1_<index>"}},
	{Recompile_V_XXX_I32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMinI32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %int %GLSL_std_450 SMin %t0_<index> %t1_<index>"}},
	{Recompile_V_XXX_I32_SVdstSVsrc0SVsrc1,       ShaderInstructionType::VMaxI32,         ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {"%t_<index> = OpExtInst %int %GLSL_std_450 SMax %t0_<index> %t1_<index>"}},
    {Recompile_VCvtPkrtzF16F32_SVdstSVsrc0SVsrc1, ShaderInstructionType::VCvtPkrtzF16F32, ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {""}},
    {Recompile_VMbcntHiU32B32_SVdstSVsrc0SVsrc1,  ShaderInstructionType::VMbcntHiU32B32,  ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {""}},
    {Recompile_VMbcntLoU32B32_SVdstSVsrc0SVsrc1,  ShaderInstructionType::VMbcntLoU32B32,  ShaderInstructionFormat::SVdstSVsrc0SVsrc1,  {""}},


    {Recompile_SMovB32_SVdstSVsrc0,            ShaderInstructionType::SMovB32,             ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_SMovB32_SVdstSVsrc0,            ShaderInstructionType::SMovkI32,            ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_SMulkI32_SVdstSVsrc0,           ShaderInstructionType::SMulkI32,            ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_V_XXX_B32_SVdstSVsrc0,          ShaderInstructionType::VBfrevB32,           ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpBitReverse %uint %t0_<index>"}},
    {Recompile_V_XXX_B32_SVdstSVsrc0,          ShaderInstructionType::VNotB32,             ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpNot %uint %t0_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VCeilF32,            ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 Ceil %t0_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VCosF32,             ShaderInstructionFormat::SVdstSVsrc0, {"%tr_<index> = OpFMul %float %t0_<index> %float_2pi", "%t_<index> = OpExtInst %float %GLSL_std_450 Cos %tr_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VExpF32,             ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 Exp2 %t0_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VFloorF32,           ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 Floor %t0_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VFractF32,           ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 Fract %t0_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VLogF32,             ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 Log2 %t0_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VRcpF32,             ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpFDiv %float %float_1_000000 %t0_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VRndneF32,           ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 RoundEven %t0_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VRsqF32,             ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 InverseSqrt %t0_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VSinF32,             ShaderInstructionFormat::SVdstSVsrc0, {"%tr_<index> = OpFMul %float %t0_<index> %float_2pi", "%t_<index> = OpExtInst %float %GLSL_std_450 Sin %tr_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VSqrtF32,            ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 Sqrt %t0_<index>"}},
    {Recompile_V_XXX_F32_SVdstSVsrc0,          ShaderInstructionType::VTruncF32,           ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 Trunc %t0_<index>"}},
    {Recompile_VCvt_XXX_F32_SVdstSVsrc0,       ShaderInstructionType::VCvtU32F32,          ShaderInstructionFormat::SVdstSVsrc0, {"%t1_<index> = OpExtInst %float %GLSL_std_450 Trunc %t0_<index>", "%t2_<index> = OpConvertFToU %uint %t1_<index>"}},
    // v_cvt_i32_f32: trunc toward zero, convert to signed int; result bits in t2
    // (uint) so the shared template can OpBitcast %float %t2 for VGPR storage.
    {Recompile_VCvt_XXX_F32_SVdstSVsrc0,       ShaderInstructionType::VCvtI32F32,          ShaderInstructionFormat::SVdstSVsrc0, {"%t1_<index> = OpExtInst %float %GLSL_std_450 Trunc %t0_<index>", "%ti_<index> = OpConvertFToS %int %t1_<index>", "%t2_<index> = OpBitcast %uint %ti_<index>"}},
    {Recompile_VCvt_XXX_F32_SVdstSVsrc0,       ShaderInstructionType::VCvtFlrI32F32,       ShaderInstructionFormat::SVdstSVsrc0, {"%t1_<index> = OpExtInst %float %GLSL_std_450 Floor %t0_<index>", "%ti_<index> = OpConvertFToS %int %t1_<index>", "%t2_<index> = OpBitcast %uint %ti_<index>"}},
    {Recompile_VCvt_XXX_F32_SVdstSVsrc0,       ShaderInstructionType::VCvtRpiI32F32,       ShaderInstructionFormat::SVdstSVsrc0, {"%t1_<index> = OpExtInst %float %GLSL_std_450 RoundEven %t0_<index>", "%ti_<index> = OpConvertFToS %int %t1_<index>", "%t2_<index> = OpBitcast %uint %ti_<index>"}},
    {Recompile_VCvtOffF32I4_SVdstSVsrc0,        ShaderInstructionType::VCvtOffF32I4,       ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VCvtF32_XXX_SVdstSVsrc0,        ShaderInstructionType::VCvtF32F16,          ShaderInstructionFormat::SVdstSVsrc0, {"%ts_<index> = OpExtInst %v2float %GLSL_std_450 UnpackHalf2x16 %t0_<index>", "%t_<index> = OpCompositeExtract %float %ts_<index> 0"}},
    {Recompile_VCvtF32_XXX_SVdstSVsrc0,        ShaderInstructionType::VCvtF32I32,          ShaderInstructionFormat::SVdstSVsrc0, {"%ti_<index> = OpBitcast %int %t0_<index>", "%t_<index> = OpConvertSToF %float %ti_<index>"}},
    {Recompile_VCvtF32_XXX_SVdstSVsrc0,        ShaderInstructionType::VCvtF32U32,          ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpConvertUToF %float %t0_<index>"}},
    {Recompile_VCvtF32_XXX_SVdstSVsrc0,        ShaderInstructionType::VCvtF32Ubyte0,       ShaderInstructionFormat::SVdstSVsrc0, {"%tb_<index> = OpBitFieldUExtract %uint %t0_<index> %uint_0 %uint_8", "%t_<index> = OpConvertUToF %float %tb_<index>"}},
    {Recompile_VCvtF32_XXX_SVdstSVsrc0,        ShaderInstructionType::VCvtF32Ubyte1,       ShaderInstructionFormat::SVdstSVsrc0, {"%tb_<index> = OpBitFieldUExtract %uint %t0_<index> %uint_8 %uint_8", "%t_<index> = OpConvertUToF %float %tb_<index>"}},
    {Recompile_VCvtF32_XXX_SVdstSVsrc0,        ShaderInstructionType::VCvtF32Ubyte2,       ShaderInstructionFormat::SVdstSVsrc0, {"%tb_<index> = OpBitFieldUExtract %uint %t0_<index> %uint_16 %uint_8", "%t_<index> = OpConvertUToF %float %tb_<index>"}},
    {Recompile_VCvtF32_XXX_SVdstSVsrc0,        ShaderInstructionType::VCvtF32Ubyte3,       ShaderInstructionFormat::SVdstSVsrc0, {"%tb_<index> = OpBitFieldUExtract %uint %t0_<index> %uint_24 %uint_8", "%t_<index> = OpConvertUToF %float %tb_<index>"}},
    {Recompile_VCvtF32F64_SVdstSVsrc0,         ShaderInstructionType::VCvtF32F64,          ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VCvtF64F32_SVdst2SVsrc0,        ShaderInstructionType::VCvtF64F32,          ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VCvtI32F64_SVdstSVsrc0,         ShaderInstructionType::VCvtI32F64,          ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VCvtF64I32_SVdst2SVsrc0,        ShaderInstructionType::VCvtF64I32,          ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VCvtF16F32_SVdstSVsrc0,         ShaderInstructionType::VCvtF16F32,          ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VF16_Unary_SVdstSVsrc0,         ShaderInstructionType::VTruncF16,          ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 Trunc %h0_<index>"}},
    {Recompile_VF16_Unary_SVdstSVsrc0,         ShaderInstructionType::VCeilF16,           ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 Ceil %h0_<index>"}},
    {Recompile_VF16_Unary_SVdstSVsrc0,         ShaderInstructionType::VFloorF16,          ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 Floor %h0_<index>"}},
    {Recompile_VF16_Unary_SVdstSVsrc0,         ShaderInstructionType::VRndneF16,          ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 RoundEven %h0_<index>"}},
    {Recompile_VF16_Unary_SVdstSVsrc0,         ShaderInstructionType::VSqrtF16,           ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %float %GLSL_std_450 Sqrt %h0_<index>"}},
    {Recompile_VCvtF16I16_SVdstSVsrc0,         ShaderInstructionType::VCvtF16I16,         ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VCvtF16U16_SVdstSVsrc0,         ShaderInstructionType::VCvtF16U16,         ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VCvtI16F16_SVdstSVsrc0,         ShaderInstructionType::VCvtI16F16,         ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VCvtU16F16_SVdstSVsrc0,         ShaderInstructionType::VCvtU16F16,         ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VCvtPkU16U32_SVdstSVsrc0SVsrc1, ShaderInstructionType::VCvtPkU16U32,       ShaderInstructionFormat::SVdstSVsrc0SVsrc1, {""}},
    {Recompile_VCvtPkI16I32_SVdstSVsrc0SVsrc1, ShaderInstructionType::VCvtPkI16I32,       ShaderInstructionFormat::SVdstSVsrc0SVsrc1, {""}},
    {Recompile_VCvtPknormU16F32_SVdstSVsrc0SVsrc1, ShaderInstructionType::VCvtPknormU16F32, ShaderInstructionFormat::SVdstSVsrc0SVsrc1, {""}},
    {Recompile_VCvtPknormI16F32_SVdstSVsrc0SVsrc1, ShaderInstructionType::VCvtPknormI16F32, ShaderInstructionFormat::SVdstSVsrc0SVsrc1, {""}},
    {Recompile_VCvtU32F64_SVdstSVsrc0,         ShaderInstructionType::VCvtU32F64,          ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VCvtF64U32_SVdst2SVsrc0,        ShaderInstructionType::VCvtF64U32,          ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VF64_Unary_SVdst2SVsrc0,        ShaderInstructionType::VTruncF64,          ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %double %GLSL_std_450 Trunc %d0_<index>"}},
    {Recompile_VF64_Unary_SVdst2SVsrc0,        ShaderInstructionType::VCeilF64,           ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %double %GLSL_std_450 Ceil %d0_<index>"}},
    {Recompile_VF64_Unary_SVdst2SVsrc0,        ShaderInstructionType::VFloorF64,          ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %double %GLSL_std_450 Floor %d0_<index>"}},
    {Recompile_VF64_Unary_SVdst2SVsrc0,        ShaderInstructionType::VRndneF64,          ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %double %GLSL_std_450 RoundEven %d0_<index>"}},
    {Recompile_VF64_Unary_SVdst2SVsrc0,        ShaderInstructionType::VRsqF64,            ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %double %GLSL_std_450 InverseSqrt %d0_<index>"}},
    {Recompile_VF64_Unary_SVdst2SVsrc0,        ShaderInstructionType::VSqrtF64,           ShaderInstructionFormat::SVdstSVsrc0, {"%t_<index> = OpExtInst %double %GLSL_std_450 Sqrt %d0_<index>"}},
    {Recompile_VFractF64_SVdst2SVsrc0,         ShaderInstructionType::VFractF64,          ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VMovB32_SVdstSVsrc0,            ShaderInstructionType::VMovB32,             ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VReadfirstlaneB32_SVdstSVsrc0,  ShaderInstructionType::VReadfirstlaneB32,   ShaderInstructionFormat::SVdstSVsrc0, {""}},
    {Recompile_VReadlaneB32_SVdstSVsrc0SVsrc1,  ShaderInstructionType::VReadlaneB32,      ShaderInstructionFormat::SVdstSVsrc0SVsrc1, {""}},
    {Recompile_VWritelaneB32_SVdstSVsrc0SVsrc1, ShaderInstructionType::VWritelaneB32,     ShaderInstructionFormat::SVdstSVsrc0SVsrc1, {""}},
    {Recompile_VNop,                           ShaderInstructionType::VNop,                ShaderInstructionFormat::Empty,       {""}},

    {Recompile_SSaveexecB64_Sdst2Ssrc02,       ShaderInstructionType::SAndSaveexecB64,     ShaderInstructionFormat::Sdst2Ssrc02, {""}, SccCheck::ExecNonZero},
    {Recompile_SSaveexecB64_Sdst2Ssrc02,       ShaderInstructionType::SAndn1SaveexecB64,   ShaderInstructionFormat::Sdst2Ssrc02, {""}, SccCheck::ExecNonZero},
    {Recompile_SSaveexecB64_Sdst2Ssrc02,       ShaderInstructionType::SOrSaveexecB64,      ShaderInstructionFormat::Sdst2Ssrc02, {""}, SccCheck::ExecNonZero},
    {Recompile_SSaveexecB64_Sdst2Ssrc02,       ShaderInstructionType::SXorSaveexecB64,     ShaderInstructionFormat::Sdst2Ssrc02, {""}, SccCheck::ExecNonZero},
    {Recompile_SSaveexecB64_Sdst2Ssrc02,       ShaderInstructionType::SAndn2SaveexecB64,   ShaderInstructionFormat::Sdst2Ssrc02, {""}, SccCheck::ExecNonZero},
    {Recompile_SSaveexecB64_Sdst2Ssrc02,       ShaderInstructionType::SOrn2SaveexecB64,    ShaderInstructionFormat::Sdst2Ssrc02, {""}, SccCheck::ExecNonZero},
    {Recompile_SSaveexecB64_Sdst2Ssrc02,       ShaderInstructionType::SNandSaveexecB64,    ShaderInstructionFormat::Sdst2Ssrc02, {""}, SccCheck::ExecNonZero},
    {Recompile_SSaveexecB64_Sdst2Ssrc02,       ShaderInstructionType::SNorSaveexecB64,     ShaderInstructionFormat::Sdst2Ssrc02, {""}, SccCheck::ExecNonZero},
    {Recompile_SSaveexecB64_Sdst2Ssrc02,       ShaderInstructionType::SXnorSaveexecB64,    ShaderInstructionFormat::Sdst2Ssrc02, {""}, SccCheck::ExecNonZero},
    {Recompile_SMovB64_Sdst2Ssrc02,            ShaderInstructionType::SMovB64,             ShaderInstructionFormat::Sdst2Ssrc02, {""}},
    {Recompile_SUnaryB32_SVdstSVsrc0,          ShaderInstructionType::SNotB32,             ShaderInstructionFormat::SVdstSVsrc0, {""}, SccCheck::NonZero},
    {Recompile_SUnaryB32_SVdstSVsrc0,          ShaderInstructionType::SBrevB32,            ShaderInstructionFormat::SVdstSVsrc0, {""}, SccCheck::NonZero},
    {Recompile_SNotB64_Sdst2Ssrc02,            ShaderInstructionType::SNotB64,             ShaderInstructionFormat::Sdst2Ssrc02, {""}, SccCheck::NonZero},
    {Recompile_SSwappcB64_Sdst2Ssrc02,         ShaderInstructionType::SSwappcB64,          ShaderInstructionFormat::Sdst2Ssrc02, {""}},
    {Recompile_SWqmB64_Sdst2Ssrc02,            ShaderInstructionType::SWqmB64,             ShaderInstructionFormat::Sdst2Ssrc02, {""}, SccCheck::NonZero},

	{Recompile_Skip,                           ShaderInstructionType::SInstPrefetch,       ShaderInstructionFormat::Imm,         {""}},
	{Recompile_Skip,                           ShaderInstructionType::SSendmsg,            ShaderInstructionFormat::Imm,         {""}},
    {Recompile_Skip,                           ShaderInstructionType::SWaitcnt,            ShaderInstructionFormat::Imm,         {""}},

    {Recompile_TBufferLoadFormatX_Vdata1VaddrSvSoffsIdxenFloat1,          ShaderInstructionType::TBufferLoadFormatX,    ShaderInstructionFormat::Vdata1VaddrSvSoffsIdxenFloat1,  {""}},
    {Recompile_TBufferLoadFormatXy_Vdata2VaddrSvSoffsIdxenFloat2,         ShaderInstructionType::TBufferLoadFormatXy,   ShaderInstructionFormat::Vdata2VaddrSvSoffsIdxenFloat2,  {""}},
    {Recompile_TBufferLoadFormatXyzw_Vdata4Vaddr2SvSoffsOffenIdxenFloat4, ShaderInstructionType::TBufferLoadFormatXyzw, ShaderInstructionFormat::Vdata4Vaddr2SvSoffsOffenIdxenFloat4,  {""}},
    {Recompile_TBufferLoadFormatXyzw_Vdata4VaddrSvSoffsIdxenFloat4,       ShaderInstructionType::TBufferLoadFormatXyzw, ShaderInstructionFormat::Vdata4VaddrSvSoffsIdxenFloat4,  {""}},

    {Recompile_V_XXX_U32_VdstSdst2Vsrc0Vsrc1,  ShaderInstructionType::VAddI32,    ShaderInstructionFormat::VdstSdst2Vsrc0Vsrc1,  {"%t_<index> = OpIAddCarry %ResTypeU %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_U32_VdstSdst2Vsrc0Vsrc1,  ShaderInstructionType::VSubI32,    ShaderInstructionFormat::VdstSdst2Vsrc0Vsrc1,  {"%t_<index> = OpISubBorrow %ResTypeU %t0_<index> %t1_<index>"}},
    {Recompile_V_XXX_U32_VdstSdst2Vsrc0Vsrc1,  ShaderInstructionType::VSubrevI32, ShaderInstructionFormat::VdstSdst2Vsrc0Vsrc1,  {"%t_<index> = OpISubBorrow %ResTypeU %t1_<index> %t0_<index>"}},
    {Recompile_V_XXX_U32_VdstSdst2Vsrc0Vsrc1Ssrc2, ShaderInstructionType::VAddCoCiU32, ShaderInstructionFormat::VdstSdst2Vsrc0Vsrc1Ssrc2A2, {""}},
    {Recompile_VMadU64U32_Vdst2Sdst2Vsrc0Vsrc1Vsrc2Pair, ShaderInstructionType::VMadU64U32, ShaderInstructionFormat::Vdst2Sdst2Vsrc0Vsrc1Vsrc2Pair, {""}},

    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpEqF32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdEqual"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpFF32,     ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual %bool %uint_0 %uint_1 ; "}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpGeF32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdGreaterThanEqual"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpGtF32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdGreaterThan"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpLeF32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdLessThanEqual"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpLgF32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdNotEqual"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpLtF32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdLessThan"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpNeqF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordNotEqual"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpNgeF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordLessThan"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpNgtF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordLessThanEqual"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpNleF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordGreaterThan"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpNlgF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordEqual"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpNltF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordGreaterThanEqual"}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpOF32,     ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFunctionCall %bool %ordered %t0_<index> %t1_<index> ; "}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpTruF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual %bool %uint_0 %uint_0 ; "}},
    {Recompile_VCmp_XXX_F32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpUF32,     ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFunctionCall %bool %unordered %t0_<index> %t1_<index> ; "}},
    {Recompile_VCmpF16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpLtF16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdLessThan"}},
    {Recompile_VCmpF16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpEqF16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdEqual"}},
    {Recompile_VCmpF16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpLeF16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdLessThanEqual"}},
    {Recompile_VCmpF16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpGtF16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdGreaterThan"}},
    {Recompile_VCmpF16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpLgF16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdNotEqual"}},
    {Recompile_VCmpF16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpGeF16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdGreaterThanEqual"}},
    {Recompile_VCmpF16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNgeF16,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordLessThan"}},
    {Recompile_VCmpF16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNlgF16,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordEqual"}},
    {Recompile_VCmpF16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNgtF16,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordLessThanEqual"}},
    {Recompile_VCmpF16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNleF16,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordGreaterThan"}},
    {Recompile_VCmpF16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNltF16,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordGreaterThanEqual"}},
    {Recompile_VCmpF64_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpLtF64,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdLessThan"}},
    {Recompile_VCmpF64_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpEqF64,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdEqual"}},
    {Recompile_VCmpF64_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpLeF64,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdLessThanEqual"}},
    {Recompile_VCmpF64_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpGtF64,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdGreaterThan"}},
    {Recompile_VCmpF64_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpLgF64,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdNotEqual"}},
    {Recompile_VCmpF64_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpGeF64,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdGreaterThanEqual"}},
    {Recompile_VCmpF64_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNgeF64,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordLessThan"}},
    {Recompile_VCmpF64_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNlgF64,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordEqual"}},
    {Recompile_VCmpF64_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNgtF64,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordLessThanEqual"}},
    {Recompile_VCmpF64_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNleF64,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordGreaterThan"}},
    {Recompile_VCmpF64_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNltF64,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordGreaterThanEqual"}},
    {Recompile_VCmpI16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpLtI16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSLessThan"}},
    {Recompile_VCmpI16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpEqI16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual"}},
    {Recompile_VCmpI16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpLeI16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSLessThanEqual"}},
    {Recompile_VCmpI16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpGtI16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSGreaterThan"}},
    {Recompile_VCmpI16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNeI16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpINotEqual"}},
    {Recompile_VCmpI16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpGeI16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSGreaterThanEqual"}},
    {Recompile_VCmpU16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpLtU16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpULessThan"}},
    {Recompile_VCmpU16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpEqU16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual"}},
    {Recompile_VCmpU16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpLeU16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpULessThanEqual"}},
    {Recompile_VCmpU16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpGtU16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpUGreaterThan"}},
    {Recompile_VCmpU16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpNeU16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpINotEqual"}},
    {Recompile_VCmpU16_XXX_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpGeU16,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpUGreaterThanEqual"}},
    {Recompile_VCmp_XXX_I32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpEqI32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual"}},
    {Recompile_VCmp_XXX_I32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpEqU32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual"}},
    {Recompile_VCmp_XXX_I32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpFI32,     ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual %bool %uint_0 %uint_1 ; "}},
    {Recompile_VCmp_XXX_I32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpGeI32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSGreaterThanEqual"}},
    {Recompile_VCmp_XXX_I32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpGtI32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSGreaterThan"}},
    {Recompile_VCmp_XXX_I32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpLeI32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSLessThanEqual"}},
    {Recompile_VCmp_XXX_I32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpLtI32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSLessThan"}},
    {Recompile_VCmp_XXX_I32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpNeI32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpINotEqual"}},
    {Recompile_VCmp_XXX_I32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpNeU32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpINotEqual"}},
    {Recompile_VCmp_XXX_I32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpTI32,     ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual %bool %uint_0 %uint_0 ; "}},
    {Recompile_VCmp_XXX_U32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpFU32,     ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual %bool %uint_0 %uint_1 ; "}},
    {Recompile_VCmp_XXX_U32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpGeU32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpUGreaterThanEqual"}},
    {Recompile_VCmp_XXX_U32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpGtU32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpUGreaterThan"}},
    {Recompile_VCmp_XXX_U32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpLeU32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpULessThanEqual"}},
    {Recompile_VCmp_XXX_U32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpLtU32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpULessThan"}},
    {Recompile_VCmp_XXX_U32_SmaskVsrc0Vsrc1,  ShaderInstructionType::VCmpTU32,     ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual %bool %uint_0 %uint_0 ; "}},
    {Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxNeqF32,  ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordNotEqual"}},
	{Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxEqF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdEqual"}},
	{Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxLeF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdLessThanEqual"}},
    {Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxGtF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdGreaterThan"}},
	{Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxLgF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdNotEqual"}},
	{Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxGeF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdGreaterThanEqual"}},
    {Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxLtF32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFOrdLessThan"}},
	{Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxNgeF32,  ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordLessThan"}},
	{Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxNlgF32,  ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordEqual"}},
	{Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxNgtF32,  ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordLessThanEqual"}},
    {Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxNleF32,  ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordGreaterThan"}},
    {Recompile_VCmpx_XXX_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxNltF32,  ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpFUnordGreaterThanEqual"}},
    {Recompile_VCmpx_XXX_I32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxEqU32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual"}},
    {Recompile_VCmpx_XXX_I32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxNeU32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpINotEqual"}},
    {Recompile_VCmpx_XXX_I32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxLtI32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSLessThan"}},
    {Recompile_VCmpx_XXX_I32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxEqI32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpIEqual"}},
    {Recompile_VCmpx_XXX_I32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxLeI32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSLessThanEqual"}},
    {Recompile_VCmpx_XXX_I32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxGtI32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSGreaterThan"}},
    {Recompile_VCmpx_XXX_I32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxNeI32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpINotEqual"}},
    {Recompile_VCmpx_XXX_I32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxGeI32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpSGreaterThanEqual"}},
    {Recompile_VCmpx_XXX_U32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxGeU32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpUGreaterThanEqual"}},
    {Recompile_VCmpx_XXX_U32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxGtU32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpUGreaterThan"}},
    {Recompile_VCmpx_XXX_U32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxLeU32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpULessThanEqual"}},
    {Recompile_VCmpx_XXX_U32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxLtU32,   ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {"OpULessThan"}},
    {Recompile_VCmpx_F_F32_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpxFF32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {""}},
    {Recompile_VCmpx_Tru_F32_SmaskVsrc0Vsrc1, ShaderInstructionType::VCmpxTruF32,  ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {""}},
    {Recompile_VCmpx_O_F32_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpxOF32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {""}},
    {Recompile_VCmpx_U_F32_SmaskVsrc0Vsrc1,   ShaderInstructionType::VCmpxUF32,    ShaderInstructionFormat::SmaskVsrc0Vsrc1,      {""}},

    {Recompile_SCmp_XXX_I32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpEqI32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpIEqual"}},
    {Recompile_SCmp_XXX_I32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpGeI32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpSGreaterThanEqual"}},
    {Recompile_SCmp_XXX_I32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpGtI32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpSGreaterThan"}},
    {Recompile_SCmp_XXX_I32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpLgI32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpINotEqual"}},
    {Recompile_SCmp_XXX_I32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpLtI32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpSLessThan"}},
    {Recompile_SCmp_XXX_I32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpLeI32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpSLessThanEqual"}},
    {Recompile_SCmp_XXX_U32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpEqU32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpIEqual"}},
    {Recompile_SCmp_XXX_U32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpGeU32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpUGreaterThanEqual"}},
    {Recompile_SCmp_XXX_U32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpGtU32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpUGreaterThan"}},
    {Recompile_SCmp_XXX_U32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpLeU32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpULessThanEqual"}},
    {Recompile_SCmp_XXX_U32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpLtU32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpULessThan"}},
    {Recompile_SCmp_XXX_U32_Ssrc0Ssrc1,  ShaderInstructionType::SCmpLgU32,    ShaderInstructionFormat::Ssrc0Ssrc1,      {"OpINotEqual"}},

    {Recompile_VCndmaskB32_VdstVsrc0Vsrc1Smask2,   ShaderInstructionType::VCndmaskB32,  ShaderInstructionFormat::VdstVsrc0Vsrc1Smask2, {""}},

    {Recompile_VInterpMovF32_VdstVsrcAttrChan,     ShaderInstructionType::VInterpMovF32, ShaderInstructionFormat::VdstVsrcAttrChan,    {""}},
    {Recompile_VInterpP1F32_VdstVsrcAttrChan,      ShaderInstructionType::VInterpP1F32, ShaderInstructionFormat::VdstVsrcAttrChan,     {""}},
    {Recompile_VInterpP2F32_VdstVsrcAttrChan,      ShaderInstructionType::VInterpP2F32, ShaderInstructionFormat::VdstVsrcAttrChan,     {""}},

    {Recompile_V_XXX_F32_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VMadF32,    ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {"%t_<index> = OpExtInst %float %GLSL_std_450 Fma %t0_<index> %t1_<index> %t2_<index>"}},
    {Recompile_V_XXX_F32_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VFmaF32,    ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {"%t_<index> = OpExtInst %float %GLSL_std_450 Fma %t0_<index> %t1_<index> %t2_<index>"}},
    {Recompile_V_XXX_F32_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VFmaMixF32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {"%t_<index> = OpExtInst %float %GLSL_std_450 Fma %t0_<index> %t1_<index> %t2_<index>"}},
    {Recompile_VDot2cF32F16_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VDot2cF32F16, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2, {""}},
    {Recompile_VDot4cI32I8_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VDot4cI32I8,  ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2, {""}},
	{Recompile_VCubetcF32_VdstVsrc0Vsrc1Vsrc2,   ShaderInstructionType::VCubetcF32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {""}},
	{Recompile_VCubescF32_VdstVsrc0Vsrc1Vsrc2,   ShaderInstructionType::VCubescF32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {""}},
	{Recompile_VCubeIdF32_VdstVsrc0Vsrc1Vsrc2,   ShaderInstructionType::VCubeIdF32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {""}},
	{Recompile_VCubeMaF32_VdstVsrc0Vsrc1Vsrc2,   ShaderInstructionType::VCubeMaF32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {""}},
    {Recompile_V_XXX_F32_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VMadakF32,  ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {"%t_<index> = OpExtInst %float %GLSL_std_450 Fma %t0_<index> %t1_<index> %t2_<index>"}},
    {Recompile_V_XXX_F32_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VMadmkF32,  ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {"%t_<index> = OpExtInst %float %GLSL_std_450 Fma %t0_<index> %t1_<index> %t2_<index>"}},
    {Recompile_V_XXX_F32_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VMax3F32,   ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {"%tm_<index> = OpExtInst %float %GLSL_std_450 FMax %t0_<index> %t1_<index>",
                                                                                                                                  "%t_<index> = OpExtInst %float %GLSL_std_450 FMax %tm_<index> %t2_<index>"}},
    {Recompile_V_XXX_F32_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VMin3F32,   ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {"%tm_<index> = OpExtInst %float %GLSL_std_450 FMin %t0_<index> %t1_<index>",
                                                                                                                                  "%t_<index> = OpExtInst %float %GLSL_std_450 FMin %tm_<index> %t2_<index>"}},
	{Recompile_V_XXX_I32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VMin3I32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%tm_<index> = OpExtInst %int %GLSL_std_450 SMin %t0_<index> %t1_<index>",
	  "%t_<index> = OpExtInst %int %GLSL_std_450 SMin %tm_<index> %t2_<index>"}},
	{Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VMin3U32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%tm_<index> = OpExtInst %uint %GLSL_std_450 UMin %t0_<index> %t1_<index>",
	  "%t_<index> = OpExtInst %uint %GLSL_std_450 UMin %tm_<index> %t2_<index>"}},
    {Recompile_V_XXX_F32_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VMed3F32,   ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {"%t3_<index> = OpExtInst %float %GLSL_std_450 FMin %t0_<index> %t1_<index>",
                                                                                                                                  "%t4_<index> = OpExtInst %float %GLSL_std_450 FMax %t0_<index> %t1_<index>",
                                                                                                                                  "%t5_<index> = OpExtInst %float %GLSL_std_450 FMin %t4_<index> %t2_<index>",
                                                                                                                                  "%t_<index> = OpExtInst %float %GLSL_std_450 FMax %t3_<index> %t5_<index>"}},
	{Recompile_V_XXX_I32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VMed3I32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%t3_<index> = OpExtInst %int %GLSL_std_450 SMin %t0_<index> %t1_<index>",
	  "%t4_<index> = OpExtInst %int %GLSL_std_450 SMax %t0_<index> %t1_<index>",
	  "%t5_<index> = OpExtInst %int %GLSL_std_450 SMin %t4_<index> %t2_<index>",
	  "%t_<index> = OpExtInst %int %GLSL_std_450 SMax %t3_<index> %t5_<index>"}},
	{Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VMed3U32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%t3_<index> = OpExtInst %uint %GLSL_std_450 UMin %t0_<index> %t1_<index>",
	  "%t4_<index> = OpExtInst %uint %GLSL_std_450 UMax %t0_<index> %t1_<index>",
	  "%t5_<index> = OpExtInst %uint %GLSL_std_450 UMin %t4_<index> %t2_<index>",
	  "%t_<index> = OpExtInst %uint %GLSL_std_450 UMax %t3_<index> %t5_<index>"}},
	{Recompile_V_XXX_I32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VMax3I32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%tm_<index> = OpExtInst %int %GLSL_std_450 SMax %t0_<index> %t1_<index>",
	  "%t_<index> = OpExtInst %int %GLSL_std_450 SMax %tm_<index> %t2_<index>"}},
	{Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VMax3U32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%tm_<index> = OpExtInst %uint %GLSL_std_450 UMax %t0_<index> %t1_<index>",
	  "%t_<index> = OpExtInst %uint %GLSL_std_450 UMax %tm_<index> %t2_<index>"}},
    {Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VSadU32,    ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {"%td_<index> = OpFunctionCall %uint %abs_diff %t0_<index> %t1_<index>",
                                                                                                                                  "%t_<index> = OpIAdd %uint %td_<index> %t2_<index>"}},
    {Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VBfeU32,    ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {"%to_<index> = OpBitwiseAnd %uint %t1_<index> %uint_31",
                                                                                                                                  "%ts_<index> = OpBitwiseAnd %uint %t2_<index> %uint_31",
                                                                                                                                  "%t_<index> = OpBitFieldUExtract %uint %t0_<index> %to_<index> %ts_<index>"}},
	// v_bfe_i32: signed bitfield extract; offset/width masked to 5 bits like u32 form.
	// RecompilerFunc param array is fixed at 4 strings — pack intermediate ops.
	{Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VBfeI32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%to_<index> = OpBitwiseAnd %uint %t1_<index> %uint_31", "%ts_<index> = OpBitwiseAnd %uint %t2_<index> %uint_31",
	  "%ti0_<index> = OpBitcast %int %t0_<index>\n          %toi_<index> = OpBitcast %int %to_<index>\n          "
	  "%tsi_<index> = OpBitcast %int %ts_<index>\n          %tr_<index> = OpBitFieldSExtract %int %ti0_<index> %toi_<index> "
	  "%tsi_<index>",
	  "%t_<index> = OpBitcast %uint %tr_<index>"}},
	// v_bfi_b32: dst = (src0 & src1) | (~src0 & src2)
	{Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VBfiB32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%ta_<index> = OpBitwiseAnd %uint %t0_<index> %t1_<index>", "%tn_<index> = OpNot %uint %t0_<index>",
	  "%tb_<index> = OpBitwiseAnd %uint %tn_<index> %t2_<index>",
	  "%t_<index> = OpBitwiseOr %uint %ta_<index> %tb_<index>"}},
	{Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VLshlAddU32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%ts_<index> = OpBitwiseAnd %uint %t1_<index> %uint_31", "%tm_<index> = OpShiftLeftLogical %uint %t0_<index> %ts_<index>",
	  "%t_<index> = OpIAdd %uint %tm_<index> %t2_<index>"}},
	{Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VAddLshlU32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%tm_<index> = OpIAdd %uint %t0_<index> %t1_<index>", "%ts_<index> = OpBitwiseAnd %uint %t2_<index> %uint_31",
	  "%t_<index> = OpShiftLeftLogical %uint %tm_<index> %ts_<index>"}},
	{Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VAndOrB32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%tm_<index> = OpBitwiseAnd %uint %t0_<index> %t1_<index>", "%t_<index> = OpBitwiseOr %uint %tm_<index> %t2_<index>"}},
	{Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VLshlOrB32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%ts_<index> = OpBitwiseAnd %uint %t1_<index> %uint_31", "%tm_<index> = OpShiftLeftLogical %uint %t0_<index> %ts_<index>",
	  "%t_<index> = OpBitwiseOr %uint %tm_<index> %t2_<index>"}},
	// v_add3_u32: dst = src0 + src1 + src2 (wraps as uint).
	{Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2, ShaderInstructionType::VAdd3U32, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,
	 {"%ts_<index> = OpIAdd %uint %t0_<index> %t1_<index>", "%t_<index> = OpIAdd %uint %ts_<index> %t2_<index>"}},
    {Recompile_V_XXX_U32_VdstVsrc0Vsrc1Vsrc2,  ShaderInstructionType::VMadU32U24, ShaderInstructionFormat::VdstVsrc0Vsrc1Vsrc2,  {"%tu0_<index> = OpBitwiseAnd %uint %t0_<index> %uint_0x00ffffff",
                                                                                                                                  "%tu1_<index> = OpBitwiseAnd %uint %t1_<index> %uint_0x00ffffff",
                                                                                                                                  "%tm_<index> = OpFunctionCall %uint %mul_lo_uint %tu0_<index> %tu1_<index>",
                                                                                                                                  "%t_<index> = OpIAdd %uint %tm_<index> %t2_<index>"}},

	    // clang-format on
	};

	static Core::Hashmap<ShaderInstructionTypeFormat, const RecompilerFunc*>* map = nullptr;

	if (map == nullptr)
	{
		map = new Core::Hashmap<ShaderInstructionTypeFormat, const RecompilerFunc*>();

		for (const auto& func: g_recomp_func)
		{
			ShaderInstructionTypeFormat p = {func.type, func.format};
			EXIT_IF(map->Contains(p));
			map->Put(p, &func);
		}
	}

	ShaderInstructionTypeFormat p = {type, format};

	return map->Get(p, nullptr);
}

} // namespace Kyty::Libs::Graphics

#endif // KYTY_EMU_ENABLED
