#ifndef KYTY_DEVTOOLS_INCLUDE_KYTY_DEVTOOLS_TRANSPORT_PROCESSIDENTITY_H_
#define KYTY_DEVTOOLS_INCLUDE_KYTY_DEVTOOLS_TRANSPORT_PROCESSIDENTITY_H_

#include <cstdint>

namespace Kyty::DevTools {

// Queries the current process through the host's independent identity source.
// The start token is never generated by Kyty and is nonzero only when the
// platform can prove the current process instance.
[[nodiscard]] bool QueryCurrentProcessIdentity(uint64_t* pid, uint64_t* start_token) noexcept;

} // namespace Kyty::DevTools

#endif /* KYTY_DEVTOOLS_INCLUDE_KYTY_DEVTOOLS_TRANSPORT_PROCESSIDENTITY_H_ */
