#!/usr/bin/env python3
"""External, fixture-specific image/action oracle for the playable runner.

The JSON contract uses schema ``kyty_scene_checkpoint_v1``, an anonymous
``fixture`` label, and ``kind`` (gameplay/menu/boot/non_gameplay). ``before`` and
``after`` each name a reviewed reference PNG (``image``, relative to this JSON,
and pinned ``sha256``). ``scene_regions`` is a nonempty list of normalized
``box`` [x0,y0,x1,y1] / ``max_mean_error`` pairs. ``response`` specifies another
box, max_mean_error, pixel_delta and min_changed_ratio for the expected action.
``action`` supplies pad_sequence, milestones, min_present_delta and min_settle_s.

References are independent of the material baseline and are never generated by
the runner. Region comparisons measure RGB error on a bounded normalized grid;
they recognize only the declared checkpoint, not arbitrary gameplay. A changed
frame alone is insufficient: it must match the expected after-reference and
be distinguishable from the before-reference in the response region.
"""

from __future__ import annotations

import hashlib
import json
import math
import struct
from pathlib import Path
from typing import Any


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_png(capture_mod: Any, path: Path) -> Any:
    # Bound decoded storage before asking the image backend to allocate it.
    with path.open("rb") as stream:
        header = stream.read(24)
    if len(header) != 24 or not header.startswith(b"\x89PNG\r\n\x1a\n") or header[12:16] != b"IHDR":
        raise ValueError("checkpoint requires a PNG image")
    width, height = struct.unpack(">II", header[16:24])
    if not width or not height or width * height > 4096 * 4096:
        raise ValueError("checkpoint image extent out of bounds")
    return capture_mod.load_image(path)


def number(value: Any, low: float, high: float) -> float:
    if isinstance(value, bool) or not isinstance(value, (float, int)):
        raise ValueError("checkpoint requires a numeric bound")
    value = float(value)
    if not math.isfinite(value) or not low <= value <= high:
        raise ValueError("checkpoint bound out of range")
    return value


def region(spec: dict[str, Any]) -> tuple[float, float, float, float]:
    box = tuple(number(v, 0, 1) for v in spec["box"])
    if len(box) != 4 or box[0] >= box[2] or box[1] >= box[3]:
        raise ValueError("checkpoint region must have positive area")
    number(spec["max_mean_error"], 0, 64)
    return box


def difference(a: Any, b: Any, box: tuple[float, ...], pixel_delta: float = 1) -> dict[str, float]:
    # At most 16384 samples per region, independent of source resolution.
    nx = min(128, max(1, int(min(a.width, b.width) * (box[2] - box[0]))))
    ny = min(128, max(1, int(min(a.height, b.height) * (box[3] - box[1]))))
    error = changed = 0.0
    for y in range(ny):
        v = box[1] + (y + 0.5) * (box[3] - box[1]) / ny
        for x in range(nx):
            u = box[0] + (x + 0.5) * (box[2] - box[0]) / nx
            pa = a.pixel(min(a.width - 1, int(u * a.width)), min(a.height - 1, int(v * a.height)))
            pb = b.pixel(min(b.width - 1, int(u * b.width)), min(b.height - 1, int(v * b.height)))
            delta = [abs(pa[i] - pb[i]) for i in range(3)]
            error += sum(delta) / 3
            changed += max(delta) >= pixel_delta
    return {"mean_error": error / (nx * ny), "changed_ratio": changed / (nx * ny)}


class SceneCheckpoint:
    def __init__(self, path: Path, capture_mod: Any):
        if path.stat().st_size > 65536:
            raise ValueError("checkpoint contract too large")
        payload = path.read_bytes()
        self.contract = json.loads(payload)
        self.sha256 = hashlib.sha256(payload).hexdigest()
        c = self.contract
        if c["schema"] != "kyty_scene_checkpoint_v1" or not isinstance(c["fixture"], str) or not c["fixture"]:
            raise ValueError("invalid checkpoint identity")
        if c["kind"] not in ("gameplay", "menu", "boot", "non_gameplay"):
            raise ValueError("invalid checkpoint kind")
        if not 1 <= len(c["scene_regions"]) <= 16:
            raise ValueError("checkpoint needs 1..16 scene regions")
        for spec in c["scene_regions"]:
            region(spec)
        response = c["response"]
        region(response)
        number(response["pixel_delta"], 1, 255)
        number(response["min_changed_ratio"], 0.0001, 1)
        action = c["action"]
        if not isinstance(action["pad_sequence"], list) or not 1 <= len(action["pad_sequence"]) <= 64:
            raise ValueError("checkpoint needs a bounded action sequence")
        if not number(action["min_present_delta"], 1, 10000).is_integer():
            raise ValueError("checkpoint present delta must be an integer")
        number(action["min_settle_s"], 0, 30)
        milestones = action["milestones"]
        for key in ("min_pad_taps", "min_guest_read_state_samples", "min_guest_read_samples"):
            if not number(milestones.get(key, 0), 0, 100000).is_integer():
                raise ValueError("checkpoint input counts must be integers")
        if "min_pad_taps" not in milestones:
            raise ValueError("checkpoint must declare its tap count (zero for holds)")
        for step in action["pad_sequence"]:
            tool = step["tool"]
            if tool in ("pad_tap", "pad_down", "pad_up"):
                if not isinstance(step["button"], str) or not step["button"]:
                    raise ValueError("invalid checkpoint action")
                if tool == "pad_down":
                    number(step["hold_s"], 0.001, 30)
            elif tool == "pad_axis":
                axis = step.get("axis")
                value = step.get("value")
                if axis not in ("left_x", "left_y", "right_x", "right_y"):
                    raise ValueError("invalid checkpoint axis")
                if isinstance(value, bool) or not isinstance(value, int) or not 0 <= value <= 255:
                    raise ValueError("invalid checkpoint axis value")
                if "hold_s" in step:
                    number(step["hold_s"], 0, 30)
            else:
                raise ValueError("invalid checkpoint action")
        if sum(step["tool"] == "pad_tap" for step in action["pad_sequence"]) != milestones["min_pad_taps"]:
            raise ValueError("checkpoint tap count does not match its sequence")
        self.capture_mod = capture_mod
        self.references = {}
        self.reference_hashes = {}
        for role in ("before", "after"):
            reference = c[role]
            image_path = (path.parent / reference["image"]).resolve()
            if image_path.stat().st_size > 32 * 1024 * 1024 or digest(image_path) != reference["sha256"]:
                raise ValueError("checkpoint reference hash/size mismatch")
            self.references[role] = load_png(capture_mod, image_path)
            self.reference_hashes[role] = reference["sha256"]
        ref_delta = difference(self.references["before"], self.references["after"],
                               region(response), response["pixel_delta"])
        if (ref_delta["changed_ratio"] < response["min_changed_ratio"]
                or ref_delta["mean_error"] <= 2 * response["max_mean_error"]):
            raise ValueError("checkpoint references do not distinguish the expected response")

    def match(self, path: Path, role: str) -> dict[str, Any]:
        image = load_png(self.capture_mod, path)
        errors = [difference(image, self.references[role], region(spec))["mean_error"]
                  for spec in self.contract["scene_regions"]]
        return {"matches": all(error <= spec["max_mean_error"]
                               for error, spec in zip(errors, self.contract["scene_regions"])),
                "region_errors": errors}

    def evaluate(self, before: dict[str, Any], after: dict[str, Any], action: dict[str, Any]) -> dict[str, Any]:
        result = {"contract_sha256": self.sha256, "fixture": self.contract["fixture"],
                  "kind": self.contract["kind"], "reference_sha256": self.reference_hashes,
                  "before": {}, "after": {}, "action": action, "checks": {}}
        checks = result["checks"]
        checks["gameplay_checkpoint"] = self.contract["kind"] == "gameplay"
        for role, record in (("before", before), ("after", after)):
            path = Path(record["path"]) if record.get("path") else None
            bound = (path is not None and path.is_file() and record.get("source") == "kyty_agent.capture"
                     and digest(path) == record.get("sha256"))
            match = self.match(path, role) if bound else {"matches": False}
            checks[role + "_scene"] = bool(bound and match["matches"])
            result[role] = {**{k: v for k, v in record.items() if k != "path"}, **match}
        checks["capture_input_order"] = bool(
            before.get("present", 0) > 0 and after.get("present", 0) > action.get("end_present", 0)
            >= action.get("start_present", 0) >= before.get("present", 0)
        )
        checks["action_delivered"] = bool(action.get("delivery_checks")) and all(action["delivery_checks"].values())
        checks["action_settled"] = bool(action.get("settled"))
        checks["expected_response"] = False
        if checks["before_scene"] and checks["after_scene"]:
            a = load_png(self.capture_mod, Path(before["path"]))
            b = load_png(self.capture_mod, Path(after["path"]))
            spec = self.contract["response"]
            box = region(spec)
            before_error = difference(a, self.references["before"], box)["mean_error"]
            after_error = difference(b, self.references["after"], box)["mean_error"]
            wrong_before_error = difference(a, self.references["after"], box)["mean_error"]
            wrong_after_error = difference(b, self.references["before"], box)["mean_error"]
            delta = difference(a, b, box, spec["pixel_delta"])
            checks["expected_response"] = (before_error <= spec["max_mean_error"]
                and after_error <= spec["max_mean_error"] and wrong_before_error > spec["max_mean_error"]
                and wrong_after_error > spec["max_mean_error"] and delta["changed_ratio"] >= spec["min_changed_ratio"])
            result["response"] = {**delta, "before_error": before_error, "after_error": after_error,
                                  "wrong_before_error": wrong_before_error, "wrong_after_error": wrong_after_error}
        return result
